spring:
  application:
    name: vehicle-services

  jpa:
    hibernate:
      ddl-auto: create-drop


  # Configuración para TiDB (Protocolo MySQL)
  datasource:
    url: ${SPRING_DATASURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

#Eureka: Servicio de registro de direcciones para la ApiGateway
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
  instance:
    # Esto es vital en Cloud Run para que Eureka no use IPs internas que cambian
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
#FeignClient: Servicio que permite la comunicacion entre microservicios
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000