name: Deploy vehicle to Oracle Free Tier

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy vehicle-services to Oracle Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/proyecto-web/Vehicle_Services
            git pull origin master
            
            cd ~/proyecto-web
            docker-compose up -d --build vehicle-services
